BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES += "${LAYERDIR}/classes/*.bb*"

WKS_SEARCH_PATH:append = ":${LAYERDIR}/files/wic"

LAYERSERIES_COMPAT_magnesium = "wrynose"
