#@TYPE: Machine
#@NAME: Luckfox Lyra PI B+W
#@DESCRIPTION: Luckfox Lyra PI B+W RK3506B machine for magnesium-core

require conf/machine/include/arm/armv7a/tune-cortexa7.inc

MACHINEOVERRIDES =. "rk3506:"

DEFAULTTUNE ?= "cortexa7thf-neon-vfpv4"

# Kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-rockchip-rk3506"
PREFERRED_VERSION_linux-rockchip-rk3506 = "6.6%"

# Boot variables
KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "rockchip/rk3506b-luckfox-lyra-pi-sd.dtb"

# Keep this minimal for your UART + network target.
MACHINE_FEATURES = "kernel26 serial ethernet usbhost usbgadget ext2"

# Useful defaults for small embedded boards.
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

# U-Boot Bootloader
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-rockchip"
UBOOT_MACHINE = "rk3506_luckfox_defconfig"
